/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ColumnsTable;

import components.StretchIcon;
import helpers.UIHelper;
import interfaces.SortingControlsCellListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.apache.batik.swing.svg.JSVGComponent;

/**
 *
 * @author juanv
 */
public class SortingControlsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SortingControlsPanel
     */
    public SortingControlsPanel() {
        initComponents();
        btnSendToTop.setIcon(new StretchIcon(getClass().getResource("/icons/double-arrow-up.png"), true));
        btnSendUp.setIcon(new StretchIcon(getClass().getResource("/icons/arrow-up.png"), true));
        btnSendToBottom.setIcon(new StretchIcon(getClass().getResource("/icons/double-arrow-down.png"), true));
        btnSendDown.setIcon(new StretchIcon(getClass().getResource("/icons/arrow-down.png"), true));
    }

    public void initSortingActionsListener(SortingControlsCellListener listener, int row) {
        btnSendToTop.addActionListener(e -> {
            listener.onSendToTopClicked(row);
        });
        btnSendToBottom.addActionListener(e -> {
            listener.onSendToBottomClicked(row);
        });
        btnSendUp.addActionListener(e -> {
            listener.onSendUpClicked(row);
        });
        btnSendDown.addActionListener(e -> {
            listener.onSendDownClicked(row);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSendToBottom = new ui.ColumnsTable.IconButton();
        btnSendToTop = new ui.ColumnsTable.IconButton();
        btnSendUp = new ui.ColumnsTable.IconButton();
        btnSendDown = new ui.ColumnsTable.IconButton();

        btnSendToBottom.setPreferredSize(new java.awt.Dimension(19, 19));

        btnSendToTop.setPreferredSize(new java.awt.Dimension(19, 19));

        btnSendUp.setPreferredSize(new java.awt.Dimension(19, 19));

        btnSendDown.setPreferredSize(new java.awt.Dimension(19, 19));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(btnSendToTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendToBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSendToBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendToTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.ColumnsTable.IconButton btnSendDown;
    private ui.ColumnsTable.IconButton btnSendToBottom;
    private ui.ColumnsTable.IconButton btnSendToTop;
    private ui.ColumnsTable.IconButton btnSendUp;
    // End of variables declaration//GEN-END:variables

}
