/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ColumnsTable;

import components.StretchIcon;
import helpers.UIHelper;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.apache.batik.swing.svg.JSVGComponent;

/**
 *
 * @author juanv
 */
public class SortingControlsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SortingControlsPanel
     */
    public SortingControlsPanel() {
        initComponents();

        btnSendToTop.setIcon(new StretchIcon(getClass().getResource("/icons/double-arrow-up_1.png"), true));
        btnSendUp.setIcon(new StretchIcon(getClass().getResource("/icons/arrow-up_1.png"), true));
        btnSendToBottom.setIcon(new StretchIcon(getClass().getResource("/icons/double-arrow-down.png"), true));
        btnSendDown.setIcon(new StretchIcon(getClass().getResource("/icons/arrow-down.png"), true));
              

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSendToBottom = new javax.swing.JButton();
        btnSendToTop = new javax.swing.JButton();
        btnSendUp = new javax.swing.JButton();
        btnSendDown = new javax.swing.JButton();

        btnSendToBottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        btnSendToBottom.setMaximumSize(new java.awt.Dimension(37, 37));
        btnSendToBottom.setMinimumSize(new java.awt.Dimension(37, 37));
        btnSendToBottom.setPreferredSize(new java.awt.Dimension(37, 37));

        btnSendToTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        btnSendToTop.setMaximumSize(new java.awt.Dimension(37, 37));
        btnSendToTop.setMinimumSize(new java.awt.Dimension(37, 37));
        btnSendToTop.setPreferredSize(new java.awt.Dimension(37, 37));

        btnSendUp.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        btnSendUp.setMaximumSize(new java.awt.Dimension(37, 37));
        btnSendUp.setMinimumSize(new java.awt.Dimension(37, 37));
        btnSendUp.setPreferredSize(new java.awt.Dimension(37, 37));

        btnSendDown.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        btnSendDown.setMaximumSize(new java.awt.Dimension(37, 37));
        btnSendDown.setMinimumSize(new java.awt.Dimension(37, 37));
        btnSendDown.setPreferredSize(new java.awt.Dimension(37, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendToTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendToBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSendToBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendToTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendDown;
    private javax.swing.JButton btnSendToBottom;
    private javax.swing.JButton btnSendToTop;
    private javax.swing.JButton btnSendUp;
    // End of variables declaration//GEN-END:variables
}
